name: Run index.js

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  run-indexjs:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Run index.js
      run: |
        node index.js
